### ISSUE TITLE
Clicking on an app on 2nd monitor wrongly enables PiP

### ISSUE THREAD

**Issue by Write** [vordenken/AutoPiP#10]
1. Open YouTube video
2. Click on any windows on your seconds monitor, PiP will enable for no reason on YouTube.

**Comment by vordenken** [comment]
Hey @Write,
I cannot test this but I know why...
I'll have to add more customisation options to the menu so people with multiple monitors can deactivate the feature "PiP on window change". Or maybe I can find a fix :) Thanks for the report!

**Comment by vordenken** [comment]
Same as #9 .
