### ISSUE TITLE
Opening any extension windows wrongly enables PiP

### ISSUE THREAD

**Issue by Write** [vordenken/AutoPiP#9]
Go to youtube, click Bitwarden / Raindrop / Noir Extension > Video will go into PiP mode.

**Comment by vordenken** [comment]
Hey @Write ,
same as #10 , because this counts as "left the tab"... I will see what I can do, because this is indeed annoying.

**Comment by vordenken** [comment]
Hi @Write ,
I really tried my best but couldnt figure out a way to disable this behavior... Clicking an extension window counts as "Tab not in focus anymore".
I added different toggles in v0.4 so if you disable "PiP on Window change" this will not occur anymore. 
I'll close this issue for now. If anyone has an idea on how to really fix this, I'm open to implement it.
